services:
  app:
    container_name: aurigraveorg-app
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    image: bouncytorch/aurigrave.org:latest
    ports:
      - '3000:3000'
    restart: unless-stopped

  db:
    container_name: aurigraveorg-postgres
    healthcheck:
      interval: 5s
      retries: 10
      test:
        - CMD-SHELL
        - "pg_isready -U ${DB_USER} -d ${DB_NAME}"
      timeout: 5s
    image: postgres:18.2
    env_file:
    - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - aurigraveorg-postgres-vol:/var/lib/postgresql/18/docker

  migrate:
    command: sh -c "npx sequelize-cli db:migrate"
    container_name: aurigraveorg-migrate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    image: bouncytorch/aurigrave.org-migrate:latest

volumes:
  aurigraveorg-postgres-vol:
