services:
  app:
    container_name: aurigraveorg-app
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_NAME: "${DB_NAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      DB_USER: "${DB_USER}"
      HOSTNAME: 0.0.0.0
      NODE_ENV: production
      PORT: 3000
    image: bouncytorch/aurigrave.org:latest
    ports:
      - '3000:3000'
    restart: unless-stopped

  db:
    container_name: aurigraveorg-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
    healthcheck:
      interval: 5s
      retries: 10
      test:
        - CMD-SHELL
        - "pg_isready -U ${DB_USER} -d ${DB_NAME}"
      timeout: 5s
    image: postgres:18-alpine
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - aurigraveorg-postgres-vol:/var/lib/postgresql/data

  migrate:
    command: sh -c "npx sequelize-cli db:migrate"
    container_name: aurigraveorg-migrate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_NAME: "${DB_NAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      DB_USER: "${DB_USER}"
    image: bouncytorch/aurigrave.org-migrate:latest

volumes:
  aurigraveorg-postgres-vol:
